### ISSUE TITLE
Feature request: runways + wind info

### ISSUE THREAD

**Issue by thijsvdc** [sanhozay/PilotLog#18]
I don't know if this info is available via the API, but it would be very nice to have the departure and arrival runways in the logs, if possible even with wind information (direction+speed)

**Comment by sanhozay** [comment]
This is not a simple change. Identifying the runway is more difficult than you might think and I'm not in a position to devote the time needed at the moment I'm afraid.

**Comment by thijsvdc** [comment]
You're right, i don't know how easy/hard that would be :)
Anyway, it was just an idea, so no worries!
