### ISSUE TITLE
Where can we find version 1.2.0?

### ISSUE THREAD

**Issue by thijsvdc** [sanhozay/PilotLog#9]
Hi,

In issue #8, I can see that this would have been fixed in v1.2.0. However, this version does not seem to be available for download?

Thanks,
Thijs

**Comment by sanhozay** [comment]
Sorry, I didn't realise anyone was using it!

I never made a 1.2 release. The version I am using is the develop branch and it is so different from master that I should make it a 2.0.0 release. It has map based tracking, an altitude chart, aircraft and airport summaries. I'll try and do that over the next couple of days.

**Comment by sanhozay** [comment]
Give 2.0.0 a try ...

https://github.com/sanhozay/PilotLog/releases/tag/2.0.0

**Comment by thijsvdc** [comment]
Tbh, I'm not using it yet :)

I was actually looking at SimToolkitPro, but this does not support FGFS. When looking for alternatives, I stumbled upon your github page. It looks very interesting, so I would really like to try it out! The new features you mention in 2.0.0 makes it even a better alternative for SimToolkitPro.

2.0.0 needs Java 14, which does not seem to be available anymore?
I tried using Java15, but this throws a lot of errors. No idea if this is related to the Java version mismatch.

**Comment by sanhozay** [comment]
I've just said it requires Java 14 because that's what I have and that's what I test it on. I'll try upgrading to Java 15.

**Comment by sanhozay** [comment]
It compiles and runs fine on Java 15 (openjdk). Could you direct your error messages into a file and attach?

**Comment by thijsvdc** [comment]
Here you go:

```
# java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-Debian-1)
OpenJDK 64-Bit Server VM (build 15.0.2+7-Debian-1, mixed mode, sharing)

./PilotLog-2.0.0.jar > pilotlog.txt
```
[pilotlog.txt](https://github.com/sanhozay/PilotLog/files/6076597/pilotlog.txt)

**Comment by sanhozay** [comment]
That's a corrupt H2 database, possibly because you have a 1.1.0 version hanging around and the database schema is different in 2.0.0 to store the tracklog. Try moving the ~/.h2 directory out of the way so that it creates a new database file and logs.

**Comment by thijsvdc** [comment]
Indeed. After reading some more, and searching for the errors, I supposed it was indeed a database issue. I did remove .h2, and now it starts just fine.
Thanks a lot!
